<?php

/**
 * @file
 * Enables the use of personal and site-wide contact forms.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\NodeInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function rsvp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.rsvp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;
  }
}

